### ISSUE TITLE
Nodes with deleted children shows extend/collapse icon

### ISSUE THREAD

**Issue by MarekBiczysko** [mbraak/django-mptt-admin#298] opened 2020-07-10 14:00 UTC
Hi,

I found strange bug, can someone please confirm this behavior?

Scenario:
- Create item with children nodes
- item has expand/collapse icon, we are able to show/hide leafs(ok)
- delete all children from item
- item has no children and no extend/collapse icon (ok)
- after refreshing the page extend/collapse icon appears again despite of the fact that there are no children inside

Attached GIF file
![django_mptt_admin_issue](https://user-images.githubusercontent.com/34810846/87162535-5b579100-c2c6-11ea-87bc-ac2802049162.gif)

Second thing, what is the expected behavior of use_context_menu? I can't see any difference whether it's True or False.

My config:

```
class DraggableDjangoMpttAdmin(DjangoMpttAdminMixin, DraggableMPTTAdmin):
    pass


class ChecklistAdmin(DraggableDjangoMpttAdmin):
    tree_auto_open = True
    tree_load_on_demand = 0
    autoescape = False

    list_display = (
    ...
    )
```

Thanks!

**Comment by mbraak** [comment] 2020-07-10 14:47
I'll have a look at it.

**Comment by mbraak** [comment] 2020-07-10 15:13
I tried to reproduce the issue in the example project, but I could not reproduce the error.

Do you get the same error if you inherit from `DjangoMpttAdmin` (instead of `DjangoMpttAdminMixin, DraggableMPTTAdmin`)?

**Comment by mbraak** [comment] 2020-07-10 15:17
The `use_context_menu` is useful if you want to write custom javascript to handle the context menu. Also see https://mbraak.github.io/jqTree/#event-tree-contextmenu

I added a pr to update the docs: https://github.com/mbraak/django-mptt-admin/pull/299

**Comment by MarekBiczysko** [comment] 2020-07-13 10:20
> DjangoMpttAdmin

Same thing when inherited from DjangoMpttAdmin (side effect - tree structure is lost in regular admin grid view)

**Comment by mbraak** [comment] 2020-07-13 13:31
Ok, clear. I still have no idea what could cause this error.

**Comment by mbraak** [comment] 2020-10-14 13:52
Closing this issue because there isn't any progress. Please reopen if necessary.

**Closed by mbraak** 2020-10-14 13:52 UTC
